apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-green
data:
  index.html: |-
    <!DOCTYPE html>
    <html lang="ja">
    <head>
      <meta charset="UTF-8">
    </head>
    <body style="background-color: green">
      <h2>
        Green app.
      </h2>
    </body>
    </html>