apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue # Blueバージョンの名前
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        version: blue # Blueバージョンを表すラベル
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: index-html-blue